################################################################################
# Node-RED Stack or Compose
################################################################################
# docker stack deploy node-red --compose-file docker-compose-node-red.yml
# docker-compose -f docker-compose-node-red.yml -p myNoderedProject up
################################################################################
version: "3.7"

services:
  nodered:
    image: nodered/node-red:2.1.4
    environment:
      - TZ=America/Toronto
    ports:
      - "1881:1880"
    networks:
      - node-red-net
    volumes:
      - ../data/node-red-data:/data

# volumes:
  # node-red-data:

networks:
  node-red-net:
