version: '3.6'

services:

  node:
    # http://10.4.1.228:14808/testroute
    working_dir: /app
    build:
      context: ./nodeapp
      dockerfile: Dockerfile
    # image: nodejs
    # container_name: nodejs
    env_file: .env
    environment:
      - MONGO_HOSTNAME=dbxx 
    # expose: 
    #   - 8080
    ports:
      - "14808:5000"
    volumes:
      - ./nodeapp:/app
      # - node_modules:/home/sysdata/node_modules
    # command: ./wait-for.sh db:27017 -- /home/sysdata/node_modules/.bin/nodemon app.js
    command: node app.js

  mongo:
    image: mongo:5
    ## container_name: db
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    ports:
      - "27017:27017"
    volumes:  
      - dbdata:/data/db   

volumes:
  dbdata:
  node_modules:      
