# Generated by Django 3.2 on 2021-11-25 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_application2_vehicle2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nc2BfwNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=45, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('body', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'nc_2bfw__note',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nc2BfwTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=45, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nc_2bfw__tag',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tagg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        
        migrations.CreateModel(
            name='Nc2BfwNcM2MNc2BfwNoteNc2BfwTag',
            fields=[
                ('nc_2bfw_tag_c', models.OneToOneField(db_column='nc_2bfw__tag_c_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='blogapp.nc2bfwtag')),
            ],
            options={
                'db_table': 'nc_2bfw___nc_m2m_nc_2bfw__note_nc_2bfw__tag',
                'managed': False,
            },
        ),

        migrations.AddField(
            model_name='post',
            name='taggs',
            field=models.ManyToManyField(to='blogapp.Tagg'),
        ),
    ]
    
